# Generated by Django 5.2.4 on 2025-07-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.CharField(choices=[('loan', 'Loan'), ('utility', 'Utility'), ('subscription', 'Subscription'), ('healthcare', 'Healthcare'), ('recreation', 'Recreation'), ('misc', 'Miscellaneous')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='type',
            field=models.CharField(choices=[('asset', 'Asset'), ('expense', 'Expense'), ('income', 'Income'), ('liability', 'Liability')], default='liability', max_length=20),
        ),
    ]
