# Generated by Django 5.2.4 on 2025-07-15 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bill_category_bill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
