# Generated by Django 5.2.4 on 2025-07-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bill_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='category',
            field=models.CharField(choices=[('', ''), ('healthcare', 'Healthcare'), ('loan', 'Loan'), ('misc', 'Miscellaneous'), ('recreation', 'Recreation'), ('subscription', 'Subscription'), ('utility', 'Utility')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='type',
            field=models.CharField(choices=[('', ''), ('asset', 'Asset'), ('expense', 'Expense'), ('income', 'Income'), ('liability', 'Liability')], default='liability', max_length=20),
        ),
    ]
