# Generated by Django 5.2.4 on 2025-07-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bill_category_alter_bill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='category',
            field=models.CharField(choices=[('healthcare', 'Healthcare'), ('loan', 'Loan'), ('misc', 'Miscellaneous'), ('recreation', 'Recreation'), ('subscription', 'Subscription'), ('utility', 'Utility')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='type',
            field=models.CharField(choices=[('asset', 'Asset'), ('expense', 'Expense'), ('income', 'Income'), ('liability', 'Liability')], max_length=20, null=True),
        ),
    ]
