# Generated by Django 5.2.4 on 2025-07-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_bill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='type',
            field=models.CharField(choices=[('asset', 'Asset'), ('expense', 'Expense'), ('income', 'Income'), ('liability', 'Liability')], default='liability', max_length=20),
        ),
    ]
