# Generated by Django 5.2.4 on 2025-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_bill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
