# Generated by Django 5.2.4 on 2025-07-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_bill_reconciled'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='recurrence',
            field=models.CharField(choices=[('none', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annually', 'Annually')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='reconciled',
            field=models.BooleanField(default='False'),
        ),
    ]
