# Generated by Django 5.2.4 on 2025-07-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_bill_recurrence_alter_bill_reconciled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='recurrence',
            field=models.CharField(choices=[('none', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('annually', 'Annually')], default='none', max_length=10),
        ),
    ]
