# Generated by Django 5.2.4 on 2025-07-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_bill_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='recurrence_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
