# Generated by Django 5.2.4 on 2025-07-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_bill_recurrence_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='category',
            field=models.CharField(blank=True, choices=[('healthcare', 'Healthcare'), ('loan', 'Loan'), ('misc', 'Miscellaneous'), ('recreation', 'Recreation'), ('investment', 'Investment'), ('subscription', 'Subscription'), ('utility', 'Utility')], max_length=20, null=True),
        ),
    ]
