# Generated by Django 5.2.4 on 2026-07-24 01:31

from django.db import migrations
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_populate_household'),
    ]

    operations = [
        migrations.AlterField(
                    model_name='bill',
                    name='household',
                    field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app.household'),
                ),
    ]
